/**
 * Auto-generated by Enterprise API Importer.
 * Do not manually edit endpoints that are synchronized with the backend contract.
 * Re-generate or update with: npm run api:update
 */

export const API_ENDPOINTS = {
  auth: {
    /** Authenticate user */
    postLogin: {
      path: 'api/v1/auth/login',
      method: 'POST' as const,
    },
    /** Get current user profile */
    getMe: {
      path: 'api/v1/auth/me',
      method: 'GET' as const,
    },
  },
  users: {
    /** List users */
    getUsers: {
      path: 'api/v1/users',
      method: 'GET' as const,
      queryParams: ['page', 'pageSize', 'search'] as const,
    },
    /** Create user */
    postUsers: {
      path: 'api/v1/users',
      method: 'POST' as const,
    },
    /** Get user by ID */
    getId: {
      path: (id: string | number) => `api/v1/users/${id}`,
      rawPath: 'api/v1/users/{id}',
      method: 'GET' as const,
    },
    /** Delete user */
    deleteId: {
      path: (id: string | number) => `api/v1/users/${id}`,
      rawPath: 'api/v1/users/{id}',
      method: 'DELETE' as const,
    },
  },
} as const;

export type ApiEndpoints = typeof API_ENDPOINTS;
